import React from "react";
import Head from "next/head";
import styles from "../styles/contact.module.scss";
import Toast from "../components/Toast";
import { motion } from "framer-motion";
import {
  fluidChildrenVariants,
  fluidEnteringVariants,
  titleVariants,
  hoverVariant
} from "../effects/motionVariants";

function contact() {
  const handleSubmit = (e) => {
    e.preventDefault();
    return Toast(
      "success",
      "Thank you for getting in touch! We appreciate you contacting us Novawalks."
    );
  };

  return (
    <>
      <Head>
        <title>Novawalks | Contact Us</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className={styles.contactUs}>
        <motion.div
          variants={titleVariants}
          initial="hidden"
          animate="visible"
          className={styles.title}
        >
          <h1>Contact Us</h1>
          <p>We would love to hear from you!</p>
        </motion.div>
        <div className={styles.formContainer}>
          <motion.form
            variants={fluidEnteringVariants}
            initial="hidden"
            whileInView="visible"
            onSubmit={(e) => handleSubmit(e)}
          >
            <motion.div variants={fluidChildrenVariants} className="row">
              <div className="col-lg-6 col-md-6 col-sm-12 mt-4">
                <input
                  type="text"
                  className="form-control"
                  placeholder="Name"
                  required
                />
              </div>
              <div className="col-lg-6 col-md-6 col-sm-12 mt-4">
                <input
                  type="email"
                  className="form-control"
                  placeholder="Email"
                  required
                />
              </div>
            </motion.div>
            <motion.div
              variants={fluidChildrenVariants}
              class="form-group my-4"
            >
              <input
                type="text"
                class="form-control"
                id="formGroupExampleInput"
                placeholder="Subject"
                required
              />
            </motion.div>
            <motion.div variants={fluidChildrenVariants} class="form-group">
              <textarea
                class="form-control"
                id="exampleFormControlTextarea1"
                rows="3"
                placeholder="Your message here..."
                required
              />
            </motion.div>
            <div className="text-center">
              <motion.button
                variants={fluidChildrenVariants}
                whileHover={hoverVariant}
                type="submit"
              >
                Send message
              </motion.button>
            </div>
          </motion.form>
        </div>
      </div>
    </>
  );
}

export default contact;
